version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sap.com
      - PGADMIN_DEFAULT_PASSWORD=Initial0
    ports:
      - 8000:80
    links:
      - postgres:postgres
  attachment:
    build:
      context: ./dir
#      dockerfile: Dockerfile-alternate

volumes:
  pgdata:
  kafka:


