apiVersion: v1
kind: Pod
metadata:
  name: demo-java-app
  labels:
    app: demo-java-app
spec:
  containers:
    - name: demo-java-app
      image: demo-k8s:17-jre-headless-ubuntu
      ports:
        - containerPort: 8080
      env:
        {{range $key,$value:= .Values.env}}
        - name: {{$key}}
          value: {{$value | quote}}
        {{end}}