apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: {{ .Release.Namespace }}-dpi
spec:
  serviceOfferingName: data-privacy-integration-service
  servicePlanName: application
  parameters:
    xs-security:
      xsappname: {{ .Release.Namespace }}/xsuaa
      authorities:
        - "$ACCEPT_GRANTED_AUTHORITIES"
      oauth2-configuration:
        credential-types:
          - x509
          - binding-secret
    dppConfig:
      applicationName: dpi-{{ .Release.Namespace }}
      information:
        fullyQualifiedApplicationName: dpi-rgp-app
        applicationTitle: SAP Revenue Growth Planning
        applicationTitleKey: dpi-di-app
        cacheControl: "no-cache"
        modules:
          - fullyQualifiedModuleName: dpi-rgp-app
            applicationURL: https://dpi-enablement-skeleton.cfapps.us21.hana.ondemand.com
            endPoints:
              - type: rest
                serviceName: manage-order-proposal
                serviceTitle: Order Proposals
                serviceURI: "/api/v1"
                annotationProviderRestEndPoint: "/api/v1/dpp/metadata"
      deletion:
        applicationGroupName: dpi-{{ .Release.Namespace }}
        applicationGroupDescription: Revenue Growth Planning
        applicationGroupDescriptionKey: RGP
        applicationGroupBaseURL: https://api.{{ .Values.nsDomain }}
        dataSubjects:
          - dataSubjectRole: Supplier
            dataSubjectDescription: Supplier
            dataSubjectDescriptionKey: SUPPLIER
            dataSubjectBaseURL: https://api.{{ .Values.nsDomain }}
            dataSubjectInformationEndPoint: "/dpp/drm/manage-order-proposal/v1/dataSubjectInformation"
            dataSubjectDeletionEndPoint: "/dpp/drm/manage-order-proposal/v1/dataSubjectDeletion"
            dataSubjectsDestroyingEndPoint: "/dpp/drm/manage-order-proposal/v1/dataSubjectDestroying"
            legalEntity:
              legalEntity: RGP_Tenant
              legalEntityDescription: RGP_Tenant
              legalEntityDescriptionKey: RGP_Tenant
              legalEntityValueHelpEndPoint: "/dpp/drm/manage-order-proposal/v1/legalEntities"
            legalGroundDiscovery: true
            legalGroundDiscoveryEndPoint: "/gdpr/drm/v1/legalGroundDiscovery"
