apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    chart: {{ .Chart.Name }}
    app: {{ .Release.Name }}
  name:  {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        env:
        - name: CS_USER
          valueFrom:
            secretKeyRef:
              name: cs-kafka
              key: CS_USER
        - name: CS_HOST
          valueFrom:
            secretKeyRef:
              name: cs-kafka
              key: CS_HOST
        volumeMounts:
        - name: kafka
          mountPath: /etc/cs-kafka
      volumes:
        - name: kafka
          secret:
            secretName: cs-kafka
status: {}
