kind: Service
apiVersion: v1
metadata:
  name: the-service
spec:
  selector:
    deployment: hello
  type: LoadBalancer
#  clusterIP: 10.107.6.22
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080
