apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4zMjE=

#  echo -n "admin" | base64
#  echo -n "admin321" | base64
#  kubectl create -f secret-demo.yaml
#  kubectl get secret
#  kubectl describe secret mysecret
#  kubectl get secret mysecret -o yaml